### ISSUE TITLE
Update Newtonsoft.Json dependency to fix severe known vulnerability

### ISSUE THREAD

**Issue by MiroKentico** [kontent-ai/delivery-sdk-net#338]
As the current version of Newtonsoft.Json contains know severe vulnerability https://github.com/advisories/GHSA-5crp-9r3c-p9vr, we should upgrade this dependency to higher version (13.0.1+) in all projects.

**Comment by dzmitryk-kontent-ai** [comment]
Current version is 13.0.1. Close it
