### ISSUE TITLE
Handle socket exceptions within RetryPolicy

### ISSUE THREAD

**Issue by erikakus** [kontent-ai/delivery-sdk-net#355]
### Motivation

The current solution provides a retry policy only for cases when WebException happens. However, connectivity issues might also occur on the local infrastructure, for which SocketException is thrown.

### Proposed solution

Would be awesome to have an extension possibility for handled exception types and response statuses OR just include SocketException handling into DefaultRetryPolicy along with WebExceptions

### Additional context

https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socketexception?view=net-7.0

**Comment by dzmitryk-kontent-ai** [comment]
Hi @erikakus. Thank you for the feedback and proposal. We will discuss it and let you know what we can do

**Comment by dzmitryk-kontent-ai** [comment]
Hi @erikakus. Could you please describe your use-case? Just to let us correctly understand the problem which SocketException should solve and to provide a proper solution for you.
And if you want to help us even better, you can include the PR as well 🙂 We welcome the contributions and contributors as well!
Thank you.

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a while since the last update here.

If we missed anything on this issue or if you want to keep it open, please reply here. 

Thanks for being a part of the Kontent.ai community!
