### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by novakv541** [kontent-ai/delivery-sdk-net#360]
May you migrate this project to .NET 7, please?

Thanks

**Comment by Simply007** [comment]
Hello @novakv541,

thanks for the issue. May I ask you to add the information asked in the template? I know it seems boring, but the provided information would help us decide how to approach the issue.

The template is following:

```plain
### Motivation

Why is this feature required? What problems does it solve?

### Proposed solution

An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.
```

**Comment by Simply007** [comment]
Linking related issues: 
* https://github.com/kontent-ai/model-generator-net/issues/174
* https://github.com/kontent-ai/management-sdk-net/issues/230

**Comment by novakv541** [comment]
### Motivation

.NET 6 is missing functionalities that .NET 7 has (caching) that we want to use for our .NET based Kotnent.ai project.

### Proposed solution

Upgrade to .NET 7.

### Additional context

https://www.honlsoft.com/blog/2022-09-24-output-caching-in-asp-net-core

**Comment by novakv541** [comment]
@Simply007 May I ask about your prioritization, please? We need to start developing ASAP.

Thanks

**Comment by Simply007** [comment]
> ### Motivation
> .NET 6 is missing functionalities that .NET 7 has (caching) that we want to use for our .NET based Kotnent.ai project.
> 
> ### Proposed solution
> Upgrade to .NET 7.
> 
> ### Additional context
> https://www.honlsoft.com/blog/2022-09-24-output-caching-in-asp-net-core

Correct me if I am wrong, but you can create .NET 7 application and use .NET 6 targetted libraries.

I have just tested out .NET 7 MVC application using Delivery SDK as well as registering 2 first routes from the [Caching article](https://www.honlsoft.com/blog/2022-09-24-output-caching-in-asp-net-core).  Everything is working just fine.

The compatibility should be OK by the [official breaking change statement my MS](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support).

**Comment by novakv541** [comment]
Hi,
We've tested it also and confirmed that it's working.

Thanks
