### ISSUE TITLE
Add SyncAPI support

### ISSUE THREAD

**Issue by arguit** [kontent-ai/delivery-sdk-net#371]
### Motivation

Kontent feature SyncAPI will be released/updated soon and it should be available through DeliveryAPI as well.

### Proposed solution

Introduce SyncAPI support into DeliverClient.

### Additional context

[SyncAPI Documentation](https://kontent.ai/learn/reference/openapi/sync-api/)

### Release date

2023-04-12

**Comment by dzmitryk-kontent-ai** [comment]
Released with SDK v. 17.6.0
