### ISSUE TITLE
Rename "project" to "environment"

### ISSUE THREAD

**Issue by michali-kontent-ai** [kontent-ai/delivery-sdk-net#377]
### Motivation

According to Kontent.ai documentation, the "project" is renamed to "environment" to correspond with the project/environment structure in Kontent.ai UI. So all, that is related to environments, should be also renamed in SDK.

### Proposed solution

Rename all mentions about "project" to "environment" (primarily projectId -> environmentId).

### Additional context

[Delivery REST API documentation](https://kontent.ai/learn/reference/openapi/delivery-api/)

**Comment by Simply007** [comment]
Internal link: DEVREL-944
