### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/delivery-sdk-net#389]
There is a broken link to https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/rich-text/resolving-item-links.md in the docs folder here https://github.com/kontent-ai/delivery-sdk-net/tree/master/docs

**Comment by pokornyd** [comment]
thanks for bringing this to our attention. there were multiple broken links, fixed in https://github.com/kontent-ai/delivery-sdk-net/commit/665b34bb0263eb781ab7e721d74e7282e6bc8b87
